name: Terraform Apply

on:
  workflow_call:
    inputs:
      tfstateFile:
        required: true
        type: string
    
defaults:
  run:
    working-directory: ./src

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: AWSGitopsLabSession
        aws-region: us-east-1
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
    - name: Terraform Init
      id: init
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.AWS_TF_BUCKET_NAME }}" \
          -backend-config="key=${{ inputs.tfstateFile }}" \
          -backend-config="region=us-east-1"
    - name: Terraform Validate
      id: validate
      run: terraform validate
    - name: Terraform Plan
      id: plan
      run: terraform plan -var-file=./environments/dev.tfvars -no-color -input=false -out "out.plan"
    - name: Terraform apply
      id: apply
      run: terraform apply "out.plan"